 - packages and modules using oops
   - similar to packages and modules in python ,but here dealing  with objects and class
   - packages(folder) - collection of modules 
   - module(py.folder) - collecction of function and class
   - acessing modules using import keyword
     - from foldername import file(.py)

In [3]:
from packages import Oops

In [4]:
dir(Oops)

['Mymath',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']

In [7]:
obj = Oops.Mymath(9,9)
print(obj.add())

18


In [15]:
from packages.Oops import Mymath

In [16]:
print(dir(Mymath))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_init_', 'add']


In [8]:
from packages.Oops2 import Modu

In [10]:
print(dir(Modu))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'isEven', 'power']


In [11]:
ob = Modu
print(ob.power(2,5))

32


In [12]:
print(ob.isEven(7))

False


- Data science
  -  organising, processing ,and analysing purpose
  - involves diffrent disciplines like mathmatical  and stastical  modeling
  - exracting data from source
  - apply for data visualisation
  - nearly 20 python libraries have for data science
      - scipy
      - tensorflow
      - numpy
      - pandas
      - matplotlib
      

- Numpy
    - numerical python
    - fundamenttal package for scientific computing
    - pyhon library provides multidimensional array array object
- installation
  - pop install numpy(windows)
  - sudo apt-get install python3 numpy
  

In [2]:
import numpy as np
np.__version__

'1.20.1'

In [3]:
np?

In [5]:
# creting of arry
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([1,2,3,5.7])

array([1. , 2. , 3. , 5.7])

In [7]:
np.array([1,2,3,4],dtype='int64')

array([1, 2, 3, 4], dtype=int64)

In [8]:
np.array([1,2,3,4],dtype='float')

array([1., 2., 3., 4.])

In [10]:
np.array([1,2,3,5.7],dtype='int')

array([1, 2, 3, 5])

In [56]:
np.array([range(i,i+3) for i in [2,4,6,]])

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [16]:
print(np.dtype)

<class 'numpy.dtype'>


In [17]:
print(dir(np.dtype))

['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'alignment', 'base', 'byteorder', 'char', 'descr', 'fields', 'flags', 'hasobject', 'isalignedstruct', 'isbuiltin', 'isnative', 'itemsize', 'kind', 'metadata', 'name', 'names', 'ndim', 'newbyteorder', 'num', 'shape', 'str', 'subdtype', 'type']


In [18]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
# ndim() -- no of dimenssions of an array
a.ndim

1

In [25]:
a.dtype

dtype('int32')

In [27]:
# shape in tuple format
a.shape

(5,)

In [28]:
# no of elements
a.size

5

In [29]:
# return each item size in bytes
a.itemsize

4

In [31]:
# u11 --- unicode string of max length 11 
b = np.array([100,78,56,'python'])
b

array(['100', '78', '56', 'python'], dtype='<U11')

In [32]:
# creating nd array
c = np.array([1,5,7])
c = np.append(c,'a')
c

array(['1', '5', '7', 'a'], dtype='<U11')

In [33]:
c = np.append(c,[2,4,6,8])
c

array(['1', '5', '7', 'a', '2', '4', '6', '8'], dtype='<U11')

In [34]:
# creating ndarray using range()
# range(startvalue,endvalue,stepvalue)
r = np.array(range(1,9,2))
print(r)
print(type(r))

[1 3 5 7]
<class 'numpy.ndarray'>


In [35]:
a = np.arange(1,11)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [36]:
#nbytes -- checking memory space occupied by an array
a.nbytes

40

In [38]:
print(a.itemsize)   # checking each element size

4


In [39]:
print(len(a))

10


In [40]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full((2,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [55]:
# linspace -- create an array with evenly space betwen ranges
h = np.linspace(0,1,5)
h

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
data = np.random.randint(1,20)
data

6

In [53]:
data = np.random.randint(1,20,size=(4,4))
data

array([[ 9, 12, 14, 16],
       [11, 12, 16, 14],
       [14, 16, 15, 11],
       [10, 15, 18,  8]])

In [50]:
x = np.arange(10).reshape((5,2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])